### ISSUE TITLE
Add cog powered trip hammer

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/pyrotech-1.12#131]
* powered by cog
* consumes hammers
* animated
* must face anvil
* configurable hammer power modifier

**Comment by Foreck1** [comment]
Conceptual model for a strip hammer that follows the specified indications 
![image](https://user-images.githubusercontent.com/47757429/89722343-98db3700-d9b6-11ea-8eac-aedb7c441de4.png)
![image](https://user-images.githubusercontent.com/47757429/89722361-b9a38c80-d9b6-11ea-8a1f-257fbe774e99.png)

**Comment by Foreck1** [comment]
![image](https://user-images.githubusercontent.com/47757429/89722935-b52ea200-d9bd-11ea-93b6-f1790fe13464.png)
Blockbench file, java model and texture (90% remixed from existing pyrotech textures)
You may use these as you please

[models.zip](https://github.com/codetaylor/pyrotech-1.12/files/5046647/models.zip)

**Comment by codetaylor** [comment]
@Foreck1 Oh dang, I forgot you made this. I already made a model, but this gives me inspiration to iterate on it.
