### ISSUE TITLE
Oredict coal coke for compatibility with Immersive Engineering

### ISSUE THREAD

**Issue by DrSquidMD** [codetaylor/pyrotech-1.12#150]
IE Blast furnaces won't accept Pyrotech coal coke.
(It would also be cool if there was some compat between coal tar/creosote oil but that's less important.)

**Comment by codetaylor** [comment]
You can use CraftTweaker to add valid fuels to the Blast Furnace:

```java
//Example:
mods.immersiveengineering.BlastFurnace.addFuel(IIngredient input, int time);
mods.immersiveengineering.BlastFurnace.addFuel(<ore:plankWood>, 2000);
```

Source: https://crafttweaker.readthedocs.io/en/latest/#Mods/Immersive_Engineering/CraftTweaker_Support/Blast_Furnace/

**Comment by codetaylor** [comment]
Which oredict do I need to add the Coal Coke to?

**Comment by nihiltres** [comment]
IE uses `fuelCoke` for the item, and `blockFuelCoke` for the block.

**Comment by codetaylor** [comment]
Thanks!

Looks like I already did this in `1.3.0`:

- https://github.com/codetaylor/pyrotech-1.12/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/core/init/JsonOreDict.java#L94
- https://pyrotech.readthedocs.io/en/latest/changelog/#130
