### ISSUE TITLE
Support BetterWithMods Mechanical Power for Cog Machines

### ISSUE THREAD

**Issue by Exsolutus** [codetaylor/pyrotech-1.12#163]
Currently, Cog machines are powered by, well, cogs, which seem to draw their energy from... who knows? BetterWithMods has an extensive mechanical power system. I think this is a great opportunity for some cross-mod interaction.

**Comment by Oethever** [comment]
I second this suggestion, and support for Immersive Engineering mechanical devices (waterwheel and wind mill) would also be greatly appreciated. This would be great for modpacks using Pyrotech but going beyond it.

It could be integrated with these mods by having a config option that requires mechanical machines (bellows, etc) to be powered by such an external mechanical power source (while still requiring a cog on the machine, to keep the progression with different cog materials).

**Comment by codetaylor** [comment]
Pyrotech will not be including any explicit compatibility with third-party mods.
