### ISSUE TITLE
Leather Works compat (mainly drying)

### ISSUE THREAD

**Issue by WarlordWossman** [codetaylor/pyrotech-1.12#193]
Would be neat if you could natively dry "prepared hide" on the pyrotech (crude) drying rack if the mod leather works ( https://www.curseforge.com/minecraft/mc-mods/leather-works ) is installed.
I know this wouldn't be much work with a CT script but since both mods are early game survival themed it could be nice to ship those recipes right out of the box assuming people want them to work together if both are installed.
Beyond that I can only think of some minor stuff like having the "leather sheet" and "leather repair kit" recipes accept twines next to the vanilla strings or a shapeless recipe for "tannins" made from 4 piles of wood chips.

**Comment by WarlordWossman** [comment]
Hm, maybe a soaking pot recipe with 200 mB of tannin and the "washed hide" would be nice, that way you can get 5 hides with one bucket rather than 3 with their barrels but got the extra waiting time of 1:45 or something.

**Comment by codetaylor** [comment]
Pyrotech will not be including any explicit compatibility with third-party mods. It does however provide deep configuration options that should allow you to sculpt your own compatibility.
