### ISSUE TITLE
Pit burning doesn't work with spongeforge

### ISSUE THREAD

**Issue by SSKirillSS** [codetaylor/pyrotech-1.12#213]
**Versions:**
pyrotech-1.12.2-1.4.2
dropt-1.12.2-1.16.1
athenaeum-1.12.2-1.17.4
forge-1.12.2-14.23.5.2847
spongeforge-1.12.2-2838-7.1.7-RC3928

**Description:**
When extracting ash after pit burning is completed, the sound of receiving a drop is heard, but nothing appears in the inventory. 
This only happens on the server with a spongeforge. In singleplayer everything is fine.

**Comment by codetaylor** [comment]
For reference, this is where the ash block drops its TE's contents into the world: https://github.com/codetaylor/pyrotech/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/tech/refractory/block/BlockPitAsh.java#L57

**Comment by codetaylor** [comment]
I have incorporated the fix from Sledgehammer which hopefully fixes this issue.

https://github.com/LXGaming/Sledgehammer/blob/1.12.2/src/main/java/io/github/lxgaming/sledgehammer/mixin/pyrotech/modules/tech/refractory/tile/TileActivePileMixin.java

Fix will be available in the next feature update `1.6.0`.
