### ISSUE TITLE
Add the lit state real in lighting items and combustion machines

### ISSUE THREAD

**Issue by jonthemoron** [codetaylor/pyrotech-1.12#229]
I think it would make PT more supportive/compatible with other mods such as Tough as Nails if the lit state in the stone and refractory combustion machines was real, so that a temperature value could be assigned to them.

**Comment by codetaylor** [comment]
Looks like the combustion machines were compatible this whole time:

```json
  {
    "state": {
      "block": "pyrotech:stone_sawmill",
      "properties": {
        "type": "BOTTOM_LIT"
      }
    },
    "temperature": 300.0
  }
```

Torches are a different story, though.

**Comment by codetaylor** [comment]
Torches have been altered and this will work in `1.12.2-1.5.0`:

```json
  {
    "state": {
      "block": "pyrotech:torch_fiber",
      "properties": {
        "type": "LIT"
      }
    },
    "temperature": 300.0
  }
```
