### ISSUE TITLE
Improve first load restart message delivery

### ISSUE THREAD

**Issue by mallowcreek** [codetaylor/pyrotech-1.12#248]
#### Issue Description

Chopping block not functioning. Potential duplicate to issue #93, which was unresolved from July 2019.

#### What Happens

The chopping block can be crafted and placed, but will not accept valid items to be placed on it. When holding an item, such as minecraft:log:0, and resting the crosshair over the chopping block, no transparent placeholder item is displayed and also right-clicking the chopping block with the held item does nothing.

Scenario 1: The issue is reproducible in Offline mode launched from MultiMC on a new world and persists after exiting the client completely and restarting the client multiple times. If this test is done again in Online mode the chopping block works as intended. After starting the client in Online mode, it can be exited and loaded up again in Offline mode and will from then on work as intended. In other words, using the chopping block will function in Offline mode only if the world has been loaded in Online mode at least once. This is using only the mods pyrotech, athenaeum, and dropt.

Scenario 2: Using modpack Enigmatica 1.73b + Pyrotech and running a spongeforge (1.12.2-2838-7.1.7-RC3950) server on forge 2847, there is no hope. The issue is encountered regardless of the server being in Online or Offline mode. This is a more complicated setup and I would hope the resolution of the simpler Scenario 1 would also resolve Scenario 2, even though the behaviour is not quite consistent between the two.

#### What You Expect to Happen

I would expect the chopping block to function the same way regardless of Internet connectivity or connection mode.

#### Script

No script.

#### Crash Log

No crashes.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: N/A
* Dropt: 1.16.1
* Pyrotech: 1.4.11
* Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
Thanks for the report!

Can you please confirm that you are not using CraftTweaker when reproducing this in scenario 1?

**Comment by codetaylor** [comment]
I'm currently unable to reproduce this.

Here's what I've tried so far:

*Note: I wasn't able to load MC without running it at least once in online mode to install Forge.*

1. Create new instance in MultiMC
2. Run once in online mode -- [required to install forge](https://github.com/MultiMC/MultiMC5/issues/2086#issuecomment-354799802)
3. Install Pyrotech
4. Run in offline mode -- wood compat configs are generated
5. Run again in offline mode -- wood compat configs are loaded

... and:

1. Delete pyrotech configs
2. Add crafttweaker to mods
3. Run in offline mode -- wood compat configs are generated
4. Run again in offline mode -- wood compat configs are loaded

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.19
* Dropt: 1.16.1
* Pyrotech: 1.4.11
* Athenaeum: 1.17.4

**Comment by mallowcreek** [comment]
Thank you for your response, and my apologies for my delayed response. I believe issue is resolved. The short answer is the mod is working according to its design and the troubleshooting steps of mine involved using a fresh install for each troubleshooting test, which was intended to produce more authentic results for each test, but ultimately made the whole thing more confusing. I hadn't realized the mod wasn't designed to be fully functional on the first run, but rather it registers stuff during the first run and then on the second run it is fully functional.

As an extra feature, I don't suppose some sort of in-game notification to restart would be possible, to reduce confusion? Maybe something like the chopping block displaying a transparent exclamation point with a on-hover message, or perhaps when attempting to place the chopping block, the block won't place and instead a chat message appears that asks for a restart? In any case, the content you have added to the community is just excellent. You have done some quality work here. Thank you.

**Comment by codetaylor** [comment]
Thank you for your kind words! :)

Pyrotech does log chat messages asking the player to restart:

![image](https://user-images.githubusercontent.com/1240716/69570032-ca6cb900-0f73-11ea-9463-aec5adc29fd5.png)

Perhaps a more invasive message delivery solution is required.

**Comment by mallowcreek** [comment]
You're absolutely right. I've verified it's there just like you've said and shown in the screenshot. I can see the message getting lost in the first-time noise of a full modpack, but surely I should have seen it in my numerous tests with just pyrotech. The only thing I could suggest about the startup message itself is to color the first line red (if possible) to grab the user's attention if they're not paying attention, like me, apparently.

**Comment by lost-RD** [comment]
![javaw_tCMQ1LwRyL](https://user-images.githubusercontent.com/2283707/74580696-e625af80-4ff6-11ea-95c3-7f7dfd501fe0.png)

I'd like to suggest using this invasive method

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/120902082-2dbcba00-c5f3-11eb-9981-daae8a25b4fe.png)
