### ISSUE TITLE
Quark stone variants integration

### ISSUE THREAD

**Issue by YTFrost** [codetaylor/pyrotech-1.12#256]
**Issue description**
Quark stone variants don't have the rock items similar to what the vanilla do

**What happens**
When mining let's say Brimstone from quark, you get the Brimstone block.

**What You Expect to Happen**
Instead of getting the Brimstone block, you would get a random ammount of Brimstone rocks, like the vanilla ones.

**Note:**
I know you could say that about every mod that adds new stone, but I think Quark is unique in it's popularity

**Comment by StormbringerGTX** [comment]
Came here to request this!

**Comment by codetaylor** [comment]
Pyrotech will not be including any explicit compatibility with third-party mods.
