### ISSUE TITLE
Add support for the "Cuisine" mod

### ISSUE THREAD

**Issue by LokyLive** [codetaylor/pyrotech-1.12#26]
Hello, 
Pyrotech is an awesome mod and the Cuisine mod (https://www.curseforge.com/minecraft/mc-mods/cuisine) is really cool so could you add support for it ?

**Comment by codetaylor** [comment]
What do you mean by support?

**Comment by LokyLive** [comment]
Cuisine add some trees (atm just citrus tree but it looks pomelos and other tree will be added) , and some crafting are done with a similar looking chopping block

On the left the Cuisine mod and on the right Pyrotech
![chop2](https://user-images.githubusercontent.com/15186174/59587052-a6fc3300-90e4-11e9-9f16-2dc6faf45644.jpg)

Cuisine's chopping block can be used to chop log too by default (1log for 6 planks)
![chop1](https://user-images.githubusercontent.com/15186174/59587051-a6639c80-90e4-11e9-9d14-515b0c5104a6.jpg)

**Comment by LunariusH** [comment]
I too have this wish. Especially as pertains to using  the basins with the Firepit.

**Comment by codetaylor** [comment]
Pyrotech will not be including any explicit compatibility with third-party mods.
