### ISSUE TITLE
Support Primitive Tools hammers by default

### ISSUE THREAD

**Issue by nihiltres** [codetaylor/pyrotech-1.12#267]
A simple inter-mod compatibility addition would be to support the Primitive Tools hammers as hammers (for anvil, worktable, etc.) by default. Following is a list of those hammers that could be added to the core.cfg `HAMMER_LIST` entry:

```
primitivetools:primitive_hammer_swf;1
primitivetools:primitive_hammer_dwf;1
primitivetools:primitive_hammer_gwf;1
primitivetools:primitive_hammer_swv;1
primitivetools:primitive_hammer_dwv;1
primitivetools:primitive_hammer_gwv;1
primitivetools:primitive_hammer_swl;1
primitivetools:primitive_hammer_dwl;1
primitivetools:primitive_hammer_gwl;1
primitivetools:primitive_hammer_sbf;1
primitivetools:primitive_hammer_dbf;1
primitivetools:primitive_hammer_gbf;1
primitivetools:primitive_hammer_sbv;1
primitivetools:primitive_hammer_dbv;1
primitivetools:primitive_hammer_gbv;1
primitivetools:primitive_hammer_sbl;1
primitivetools:primitive_hammer_dbl;1
primitivetools:primitive_hammer_gbl;1
```

I've listed them all as harvest-level 1 because they're roughly equivalent in crafting cost to Pyrotech's own stone hammer.

**Comment by hron84** [comment]
Same with Primal Core gallaghers. Btw, listed hammers are working on pyro crafting table too?

**Comment by codetaylor** [comment]
Pyrotech will not be including any explicit compatibility with third-party mods. It does however provide deep configuration options that should allow you to sculpt your own compatibility.
