### ISSUE TITLE
Divergent Underground Compatibility.

### ISSUE THREAD

**Issue by SwivelDiscourse** [codetaylor/pyrotech-1.12#271]
A fairly straight forward integration, and one I’ve been attempting to do through scripts and configs, so this integration is more a matter of convenience for others rather than a personal request. 

Pyrotech and Divergent Underground have great synergy, and together they provide a great Expert Mining experience that is reminiscent of TFC or a similar "Expert" mining experience. 

Integration involves replacing DU’s materials with Pyrotech’s, or vice versa. I believe both should be options, as they let players set a sort of difficulty curve regarding Rocks.
DU and Pyrotech both add rocks, with some basic compatibility like Primitive Tools already in place. The main difference between the two is that Pyrotech Rocks are smaller and more granular than DU Rocks are as a resource. Cobble and Gravel recipes generally use 8 Pyrotech rocks(and clay for cobble). Divergent Underground Recipes use 4 for theirs(and don’t require Clay for Cobble)
DU also has its own versions of non-vanilla cobble, which do require some integration with Kilns and other machines with non-vanilla recipe integration. 

Lastly, Divergent Underground targets Vanilla, Chisel, and Quark ores and stone blocks, replacing some of them with DU versions during WorldGen. This means that some quirks of Pyrotech/Dropt don’t target DU blocks, and may ignore Tool level/quantity/quality drops with materials like Coal or Iron.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codetaylor** [comment]
Pyrotech will not be including any explicit compatibility with third-party mods.
