### ISSUE TITLE
Config option to disable tree punching

### ISSUE THREAD

**Issue by 111mzd** [codetaylor/pyrotech-1.12#302]
It'd be fitting and more realistic if there were a config option to disable harvesting wood logs without the correct tool, so that you need an axe; i.e. without the correct tool, the breaking time would be long and you wouldn't get drops.

**Comment by nebelhund** [comment]
It can be achieved with PunchMeNot mod. I use it with pyrotech and they fit each other just perfectly! 
So, IMHO, you will just "invent a bicycle" having this request done. But everything is up to you.

**Comment by codetaylor** [comment]
I have no intention of disabling tree punching by default in Pyrotech and will not be adding the feature.

Please use one of the other mods specifically designed for this purpose.
