### ISSUE TITLE
getting a crash after updating Athenaeum to the version listed

### ISSUE THREAD

**Issue by Nathan22211** [codetaylor/pyrotech-1.12#307]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

caught exception crash from pyrotech after updating its dependency, Athenaeum, to the version listed below

#### What Happens

pyrotech causes a crash

#### What You Expect to Happen

It shouldn't crash

#### Script

no script caused it

#### Crash Log

https://gist.github.com/Nathan22211/fbf30830fc752808b6fdf7b8c042af40

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CraftTweaker: 4.1.20.574
* Dropt: 1.18.0
* Pyrotech: 1.4.29
* Athenaeum: 1.19.0

**Comment by codetaylor** [comment]
You need Pyrotech `1.4.30` which I forgot to put up on CurseForge. I'll do that now.
