### ISSUE TITLE
Refractory burn recipes not showing in JEI

### ISSUE THREAD

**Issue by FrogBirddd** [codetaylor/pyrotech-1.12#308]
Issue Description

When looking in JEI, refractory burn recipes do not appear despite functioning in game

 What Happens

I open the "show all recipes" option in JEI or try to find the uses of blocks, refractory recipes do not appear in either case. However, the recipes still function in game when they are performed. This issue persists after removing both the config and crafttweaker scripts related to the mod. Non-refractory burn recipes do still appear.

 What You Expect to Happen

JEI should show the recipes without issue.

 Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CraftTweaker :4.1.20.574
* Dropt: 1.18.0
* Pyrotech: 1.4.31
* Athenaeum: 1.19.1

**Comment by codetaylor** [comment]
Can't reproduce this yet. Here are the actions I performed in the attempt:

1. Open JEI
2. Navigate to `Block of Coal`
3. Hover mouse on `Block of Coal` and press `U`
4. See Refractory Burning in tabs

![image](https://user-images.githubusercontent.com/1240716/87330026-d00c1480-c4ec-11ea-8de4-0a9b17c55272.png)

5. Click `Refractory Burning` title to show all recipes
6. See Refractory Burning in tabs

![image](https://user-images.githubusercontent.com/1240716/87330269-31cc7e80-c4ed-11ea-831f-6b137554ad6b.png)

**Comment by codetaylor** [comment]
What version of JEI?

**Comment by FrogBirddd** [comment]
4.1.5.0.2.9.6

**Comment by FrogBirddd** [comment]
I managed to find the issue, hiding the refractory block in JEI hides the recipes with it. Sorry for the concern, but thanks for helping:)
