### ISSUE TITLE
Configurable default bloom yield

### ISSUE THREAD

**Issue by ghost** [codetaylor/pyrotech-1.12#310]
#### Prologue
> I fell in love with your mod immediately after I've joined a new world with it installed. So I started to create a modpack for myself based around your mod and some fantasy. I looked at every option u left in configuration. And I like just everything.
> But... The one think I don't like at all is an ore duplication. I saw this feature in a lot of different industrial mods, where u need just a tone of ore all the time. 

#### What's next
> I started to seek how to chance such thing. And, as I use CraftTweaker since I've started to make a modpack, I found a possibility to change recipes from bloomery and other cool stuffs.
> But... It will take a lot of time to remake all bloomery recipes as I want.

#### Suggestion
> In an amazing file core.compat.Ore-Generated/Custom in every entry add a new dict `yield`, which contains `min` and `max` integers, so it will be possible to adjust yielding for each ore.

**Comment by nebelhund** [comment]
Sorry, I forgot one thing. If it's possible, pls make slag yielding also configurable in the same file.
