### ISSUE TITLE
Pyrotech conflicts with Tech Reborn's sawmill

### ISSUE THREAD

**Issue by Raithion** [codetaylor/pyrotech-1.12#315]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

For some reason, having Pyrotech installed removes the vanilla wood recipes from Tech Reborn's industrial sawmill. All other logs can successfully be sawed using Tech Reborn's sawmill, but the 6 vanilla logs have had their recipes removed. This issue only appears with Pyrotech installed.

#### What Happens

I try to place a vanilla log into Tech Reborn's sawmill, but it will not be sawed into planks. Furthermore, it shows no recipe for the item in JEI.

#### What You Expect to Happen

The intended method would be to place a vanilla log into Tech Reborn's sawmill and have it be sawed into planks. With Pyrotech installed, the recipes for sawing vanilla logs are removed.

#### Script

N/A

#### Crash Log

N/A

#### Affected Versions

* Minecraft: 1.12.2
* Forge: forge-14.23.5.2854
* CraftTweaker: CraftTweaker2-1.12-4.1.20.574
* Dropt: dropt-1.12.2-1.18.0
* Pyrotech: pyrotech-1.12.2-1.4.33
* Athenaeum: athenaeum-1.12.2-1.19.1

**Comment by codetaylor** [comment]
Yep. Pyrotech removes the vanilla wood recipes which TR probably uses to generate its wood recipes.

**Comment by codetaylor** [comment]
You'll have to add the recipes back to TR if it has a way to do that or disable the removal of the wood recipes in Pyrotech's config.
