### ISSUE TITLE
Issue with Chopping Block

### ISSUE THREAD

**Issue by TheSexyYeti** [codetaylor/pyrotech-1.12#316]
Hay the chopping block has an occasional issue where it stops working. It doesn't happen all the time. So it might be hard to reproduce. You're able to place wood and wood planks on it. But it's like the bounding box disappears and won't let you chop anything. I don't know what the issue is. The only way I've found to fix it is to delete my world and start a new game.

**Comment by codetaylor** [comment]
I have never experienced this and I have no idea what would cause it. I suspect a mod conflict.

**Comment by codetaylor** [comment]
It might be that you've run out of hunger while using it. It requires hunger to use and depletes hunger when you use it.
