### ISSUE TITLE
You're still able to chop down dynamic trees without an axe with this mod installed

### ISSUE THREAD

**Issue by Nathan22211** [codetaylor/pyrotech-1.12#317]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

*[replace]*

dynamic trees aren't affected by this mod requiring an ax to chop them down.

*[/replace]*

#### What Happens

*[replace]*

chop down a  dynamic tree in survival without an ax, you still get the logs and sticks

*[/replace]*

#### What You Expect to Happen

*[replace]*

I shouldn't be able to do this without an ax

*[/replace]*

#### Script

*[replace]*

If your issue involves a CraftTweaker script, please place a **LINK** to your script here.

**DO NOT** paste your script here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Crash Log

*[replace]*

If your issue involves a crash log, please place a **LINK** to your crash log here.

**DO NOT** paste your crash log here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CraftTweaker: (more than likely not related to this)
* Dropt: 1.18.0
* Pyrotech: 1.4.33
* Athenaeum: 1.19.1

**Comment by codetaylor** [comment]
Pyrotech doesn't add a feature to prevent you from chopping log blocks without an axe. Maybe you have another 'no tree punching' type mod that adds this feature?

This feature has been requested in #302, but it probably won't be implemented as there are other mods that do the same thing.
