### ISSUE TITLE
Obsidian hammer is assigned the incorrect material

### ISSUE THREAD

**Issue by 111mzd** [codetaylor/pyrotech-1.12#321]
After having attempted to modify the enchantability values of bone/flint tools, I've discovered that the obsidian hammer in particular seems to be assigned "athenaeum:FLINT" rather than "athenaeum:OBSIDIAN", which is what the rest of the obsidian tools appear to be assigned. 
This issue occurs on the latest version, Pyrotech 1.4.33. I used Apotheosis to modify enchantability values.

**Comment by codetaylor** [comment]
Oof. Yeah...

https://github.com/codetaylor/pyrotech-1.12/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/core/item/ItemObsidianHammer.java#L16

I'll fix it soon.

**Comment by democat3457** [comment]
btw your link in the changelog to this issue goes to the wrong repository
