### ISSUE TITLE
Biomes O' Plenty Foliage Compatibility 

### ISSUE THREAD

**Issue by mewj** [codetaylor/pyrotech-1.12#336]
Biomes O' Plenty adds different grass heights, medium and short grass, which do not drop tubers or plant fibers. Although not that big of an issue, could it possible to add a config option to change which blocks drop plant fibers? 

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CraftTweaker: 4.1.19
* Dropt: 1.18.0
* Pyrotech: 1.5.5
* Athenaeum: 1.19.2

**Comment by codetaylor** [comment]
This can already be configured using Dropt.

Pyrotech uses Dropt under the hood to alter some block drops: https://pyrotech.readthedocs.io/en/latest/droptrules/

If you disable the `grass_tall` rules in the config, you can write your own rule using Dropt.

Dropt has an export command `/dropt export` that will export all rules in memory to a .json file. Once exported, you can dig through that file to find Pyrotech's tall grass rule and use that as a template for your own.

There's also this example: https://dropt.readthedocs.io/en/latest/examples/grass_drops/

**Comment by SenZ01** [comment]
If you need a script that lets you drop plantfiber by breaking grass just hit me up on the codetaylor discord in the "#dropt" channel!
