### ISSUE TITLE
Compost bin crash

### ISSUE THREAD

**Issue by AR2000AR** [codetaylor/pyrotech-1.12#338]
#### Intro

**Updating Athenaeum to 1.19.2 fix the issue**
Please read the "Possible fix" section to get more detail on what happened.

I'm using pyrotec on a server and got a problem with the compost bin.

#### Issue Description

Placing a compost bin in the world crash the client but not the server.

#### What Happens

Just place a compost bin and the game will crash.
The player who placed the bin can't reconnect until the bin is destroyed.
The crash seem to be caused by the bin's interface (when your cursor is on the block).

##### Note

The bin is placed in the world and can be deleted with `/setblock`.

#### What You Expect to Happen

The block should be placed and the game should not crash (obviously).

#### Script

CraftTweeker does not play a role in this crash. Can be reproduced without any script present.

#### Crash Log

https://pastebin.com/Liv0LLwK

#### Possible fix

Add a minimum version for Athenaeum. The version 1.19.2 fix it.
The 1.19.1 is missing the file `com/codetaylor/mc/athenaeum/network/tile/data/TileDataItemStack`.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CraftTweaker: 4.1.19
* Dropt: 1.16.1
* Pyrotech: 1.5.5
* Athenaeum: 1.19.1

**Comment by codetaylor** [comment]
Yes, Pyrotech 1.5+ is not compatible with Athenaeum <= 1.19.1
