### ISSUE TITLE
A compatibility problem about CraftTweaker

### ISSUE THREAD

**Issue by origin-s** [codetaylor/pyrotech-1.12#340]
**I want to creates and returns a new bloomery recipe builder.
I follow the course on wiki:**
Bloomery.createBloomeryBuilder(
"bloom_from_Copper_ore",
**<**immersiveengineering:metal**>**
**<**ore:oreCopper**>**  **_//I use the Ore Dictionaries here_.**
)
.setBurnTimeTicks(14400)
.setFailureChance(0.10)
.setSlagItem(**<**pyrotech:slag**>**, 1)
.setSlagItem(**<**pyrotech:rock:0**>**, 1)
.addFailureItem(**<**pyrotech:slag**>**, 4)
.addFailureItem(**<**pyrotech:rock:0**>**, 1)
.register();
**But the craftTweaker pointed out me that I had made a mistake:**
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing pyrotech.zs:18 -- ) expected.
**I don't understand，Can I use Ore Dictionaries here?**

**Comment by codetaylor** [comment]
It looks like you need a comma after the second argument.

If you have questions about scripting, please use the Discord in the future: http://discord.codetaylor.com
