### ISSUE TITLE
Rock bag contents destroyed when placed on blocks like the decorative grass block. 

### ISSUE THREAD

**Issue by mewj** [codetaylor/pyrotech-1.12#341]
I couldn't think of a better way to describe the block in question, but the video should show what I mean. There are no other mods installed, not even crafttweaker. This issue also occurs with the rocks that Pyrotech places on the ground on world generation. 

* Minecraft: 1.12.2 
* Forge: 14.23.5.2855
* CraftTweaker: Not Installed 
* Dropt: 1.18.0
* Pyrotech: 1.5.6 
* Athenaeum: 1.19.2 

https://user-images.githubusercontent.com/75946895/105620378-1b6b7d80-5dc2-11eb-9cee-5a6bf0610af0.mp4

**Comment by codetaylor** [comment]
Thanks for the report! Fixed in `1.12.2-1.5.7`
