### ISSUE TITLE
Sudden world crash

### ISSUE THREAD

**Issue by MrRedCard** [codetaylor/pyrotech-1.12#349]
I have a server for my friends, we installed some mods including this. Every time we entered it asked for re-opening the world for some wood recipes and we couldn't chop logs in to slabs too. So I decided to re-open the world and now we get this message:

![image](https://user-images.githubusercontent.com/81360309/112712868-2edeb600-8ee3-11eb-8b1f-908b9eb948e1.png)

Is there a way to solve this?

**Comment by codetaylor** [comment]
> Every time we entered it asked for re-opening the world for some wood recipes and we couldn't chop logs in to slabs too.

This is expected behavior.

> So I decided to re-open the world and now we get this message:

I have no idea what mod would cause this. Maybe try removing mods to narrow down which mod is causing it.
