### ISSUE TITLE
ShoulderSurfing-1.12.2-1.15.1

### ISSUE THREAD

**Issue by Romoslayer** [codetaylor/pyrotech-1.12#354]
Hi so recently I put together a modpack with ShoulderSurfing-1.12.2-1.15.1 and wanted to try to host a server to play with friends and whenever I try to run the server it crashes and when I check the crash reports it says net.minecraftforge.fml.common.LoaderException: shouldersurfing Failed load class:com.teamderpy.shouldersurfing.ShoulderSurfing
and some other things Please help thank you.

Minecraft
Version : forge-1.12.2-14.23.5.2854
Mod : ShoulderSurfing-1.12.2-1.15.1

**Comment by codetaylor** [comment]
This is the issue tracker for Pyrotech, not ShoulderSurfing. I'm not the developer of ShoulderSurfing.

**Comment by Romoslayer** [comment]
Hi thanks for the help but I actually figured it out. I only needed shoulder surfing in my minecraft mods and removed it from the server mods and everything worked fine.
