### ISSUE TITLE
Hammers can't be put on the worktable

### ISSUE THREAD

**Issue by origin-s** [codetaylor/pyrotech-1.12#362]
I add a recipe of crafting table with Crt. Like this
![56736c46bf7d5af8_edit_30351169270889](https://user-images.githubusercontent.com/63846610/120893285-1de3ac80-c5d8-11eb-80c4-babd52a6b875.png) 
But I find that the iron hammer can't be put on worktable. Looking forward to yours' help.

**Comment by codetaylor** [comment]
That is correct. That is how it is currently designed.

Linked to #251

**Comment by origin-s** [comment]
> That is correct. That is how it is currently designed.
> 
> Linked to #251

Ok. Thank you.
