### ISSUE TITLE
Compost Bin TheOneProbe error

### ISSUE THREAD

**Issue by Rsslone** [codetaylor/pyrotech-1.12#364]
#### Issue Description

OneProbe error on Compost bin when adding compost.

#### What Happens

Place a compost item into the bin. 
One Probe shows the following error.
![image](https://user-images.githubusercontent.com/1240716/128100445-a1523469-3e0a-48f2-9056-1a227fbc3434.png)

#### What You Expect to Happen

For it to display progress or something else helpful.

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:1.12.2
* Forge:14.23.5.2854
* CraftTweaker:4.1.20.614
* Dropt:1.18.0
* Pyrotech:1.5.13
* Athenaeum:1.19.2

**Comment by codetaylor** [comment]
I need the log file also. Please use pastebin or another similar service and paste the link to your log file showing the error.

**Comment by codetaylor** [comment]
Currently can't reproduce this.

![image](https://user-images.githubusercontent.com/1240716/128099736-2eda929f-c5fe-4f6e-9f07-1a3ce05766f1.png)

**Comment by codetaylor** [comment]
In addition to the log, also please tell me your ToP version.

**Comment by Rsslone** [comment]
theoneprobe-1.12-1.4.28
Client Log, thought it didn't have anything that stood out from me, granted I just ctrl+f'd pyro and read through.
https://gist.github.com/Rsslone/86c3f4890e38f503dc89c366a96fd286

**Comment by codetaylor** [comment]
Thank you.

Was this single player or on a server?

**Comment by Rsslone** [comment]
On a server. Do you want the server Logs?

**Comment by codetaylor** [comment]
Yes, please. Pyrotech's ToP provider runs server-side so any errors should be logged there.

**Comment by Rsslone** [comment]
https://gist.github.com/Rsslone/35d2b185fe7da28f6097ef4209f1e113

**Comment by codetaylor** [comment]
Thank you. Reproduced on server.

**Comment by codetaylor** [comment]
Fixed in `1.12.2-1.5.14`

**Comment by Rsslone** [comment]
You're a legend, thank you.

**Comment by Rsslone** [comment]
This same issue is also found with the rock bags.

**Comment by codetaylor** [comment]
@Rsslone Can you make a new issue for it please? It's likely that I'll forget about it by the time I get the time to fix it. Thanks!
