### ISSUE TITLE
Rock Bag TheOneProbe error

### ISSUE THREAD

**Issue by Rsslone** [codetaylor/pyrotech-1.12#366]
#### Issue Description

One probe displays the following error ingame.

#### What Happens

![image](https://user-images.githubusercontent.com/1240716/129464243-4d4bbfae-3948-4804-93de-cb825d60372a.png)

https://i.imgur.com/zmHXKZb.png

#### What You Expect to Happen

For it to not do that :)

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

Minecraft:1.12.2
Forge:14.23.5.2854
CraftTweaker:4.1.20.614
Dropt:1.18.0
Pyrotech:1.5.14
Athenaeum:1.19.2

**Comment by codetaylor** [comment]
Fixed in `1.12.2-1.5.15`
