### ISSUE TITLE
Update to 1.16/1.17!

### ISSUE THREAD

**Issue by Momentariy** [codetaylor/pyrotech-1.12#367]
Update Pyrotech to Minecraft 1.16.5/1.17.1

**Comment by GManMan** [comment]
[Did you read this first?](https://github.com/codetaylor/pyrotech-1.12/blob/master/README.md)

**Comment by viveleroi** [comment]
I sure hope there's a 1.16/1.18 version "someday" too, this plus farmer's delight would make an amazing early game to a modpack.
