### ISSUE TITLE
Electric machine

### ISSUE THREAD

**Issue by RJHG56** [codetaylor/pyrotech-1.12#368]
a willmill that uses energy with an efficiency probability of 75%=3 or 100% =4 an some times 125%=5,the energy could be obtainen from other mods like immersive energy o mekanism,(idk) between  electricity mods are compatible energy

**Comment by RJHG56** [comment]
please :3

**Comment by TrashboxBobylev** [comment]
why

**Comment by GManMan** [comment]
A windmill that uses energy... why?

Also, why do you think electricity fits with pyrotech? Just play with IE if you want windmills (that produces energy, instead of using it).

**Comment by codetaylor** [comment]
Thank you for your suggestion, however I will not be implementing this.

**Comment by RJHG56** [comment]
haha, sorry, i have two problems because i write that bad, and you understand somethig else, the correct was sawmill
