### ISSUE TITLE
Bloomery Capacity affects how much slag a bloomery produces, ignoring the amount of ores

### ISSUE THREAD

**Issue by SvenParoth** [codetaylor/pyrotech-1.12#369]
#### Issue Description

I noticed that when i set the bloomery capacity to something higher than 1 (in my case 16), but only put 1 ore into it, it will still produce a lot of slag, as if i had put in 16 ore blocks. This makes it very easy to dupe ores essentially.

#### What Happens

Go to config option, set bloomery capacity to 16, restart, place bloomery, only insert 1 ore instead of 16, add fuel (i used max fuel), and let it run. It will produces a ton of slag.

#### What You Expect to Happen

Slag should scale depending on amount of ore inside the bloomery, not the capacity of the bloomery.

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Dropt: dropt-1.12.2-1.19.1.jar
* Pyrotech: pyrotech-1.12.2-1.5.15.jar
* Athenaeum: athenaeum-1.12.2-1.19.2.jar

**Comment by codetaylor** [comment]
Thanks for the report, I'll fix it soon.

**Comment by codetaylor** [comment]
Resolved in `1.12.2-1.5.16`
