### ISSUE TITLE
Allow more fluids to extinguish campfires

### ISSUE THREAD

**Issue by SeriousCreeper** [codetaylor/pyrotech-1.12#372]
Heya,

currently it looks like the campfire tile entity looks specifically for FluidRegistry.WATER when trying to extinguish it with a bucket. 
This is a bit of a rare case, but in my case im not using the vanilla water anywhere, instead i use the betweenlands swamp water. 

Would it be possible to get a config option or something that could specify what fluid is valid there? 

Cheers,
SC

**Comment by codetaylor** [comment]
Sure. I can add it to `1.12.2-1.6`. It should probably be extended to all things extinguishable: campfires, torches, and combustion machines.
