### ISSUE TITLE
Pyrotech buckets deletes objects when placing water

### ISSUE THREAD

**Issue by IC-Dyllac** [codetaylor/pyrotech-1.12#375]
#### Issue Description

When placing water with pyrotech's buckets on some placed items, the water gets placed but the item gets deleted

#### What Happens
 - When placing a water block by hand with a pyrotech's bucket on the same block of some specific things (rocks, string, redstone and rails, maybe more? ) the water gets placed and the item that was on that block disappears. This also happens when the water is placed via a dispenser with a pyrotech's bucket.

#### What You Expect to Happen

Water block should be placed correctly and the item should drop if it was breakable by water (pretty much same behaviour of a regular bucket)

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* CraftTweaker: N/A
* Dropt: 1.12.2 - 1.19.1
* Pyrotech: 1.12.2 - 1.5.20
* Athenaeum: 1.12.2 - 1.19.4

Only other mod installed was JEI

**Comment by IC-Dyllac** [comment]
As a side note, I found this issue while experimenting with this mod and Better With Mods with the HardCore Buckets module. But I suspect this issue is the culprit of the weird interaction between the two.

**Comment by codetaylor** [comment]
Fixed in `1.12.2-1.5.21` in tandem with Athenaeum `1.12.2-1.19.5`

**Comment by codetaylor** [comment]
Pyrotech's buckets deferred the in-world fluid placement to Forge's FluidUtil class which doesn't break replaceable blocks before placing the fluid. I've created a workaround in Athenaeum's FluidUtilFix class.
