### ISSUE TITLE
Thematically incorrect cob texture

### ISSUE THREAD

**Issue by Foreck1** [codetaylor/pyrotech-1.12#394]
The current texture for cob appears to be a set of bricks. The most significant difference between adobe and cob is that the former consists of previously dried bricks, whereas the latter usually makes up a monolithic structure with layers gradually added on top of previously dried ones.
This suggestion is for either, renaming the current cob block to adobe, or removing the seams in the current texture to make it a tiling block (single structure).

**Comment by codetaylor** [comment]
> whereas the latter usually makes up a monolithic structure with layers gradually added on top of previously dried ones

That's certainly correct, however cob can also be used as bricks.

https://www.google.com/search?q=cob+bricks

I'm going to leave it the way it is, but please feel free to change it in your pack. 😄
