### ISSUE TITLE
Add a config option to remove carcass from drops

### ISSUE THREAD

**Issue by juraj-hrivnak** [codetaylor/pyrotech-1.12#396]
Hello, the new hunting module is excellent. I love it. 
However, I would want to disable the carcass and keep the hides and pelts only.

So, if added, I would highly appreciate the said config.

**Comment by codetaylor** [comment]
Carcasses won't drop if they don't have anything to capture or add. Just remove all the capture / add entries in the hunting config -- two lists or maps. I don't remember what they're called off the top of my head.

**Comment by juraj-hrivnak** [comment]
Oh, right! I've removed all the entries from the `DROP_CAPTURE_LIST` but missed the `drop_map`.
Now it works, exactly how I wanted, thanks!
