### ISSUE TITLE
The scraped leather does not have recipes

### ISSUE THREAD

**Issue by Origins-Eternal** [codetaylor/pyrotech-1.12#400]
#### Issue Description

I want to craft leather, but I find the scraped leather does not have any recipes.

#### What Happens

Whether I use jei or look it up in the book, I can't see its recipe. Except for necessary mods and jei, I do not add other mods such as crafttweaker.
![2022-09-11_12 23 31](https://user-images.githubusercontent.com/63846610/189512709-17a7599a-efe4-4890-ae34-1f8f880cd3b4.png)

#### Affected Versions

* Minecraft:1.12.2
* Forge:14.23.5.2860
* Dropt:1.19.3
* Pyrotech:1.6.3
* Athenaeum:1.19.5

**Comment by codetaylor** [comment]
The scraped leather recipes use new oredict entries. It's likely that your oredict json file does not have the new entries. Please try refreshing the oredict json file.

**Comment by Origins-Eternal** [comment]
> The scraped leather recipes use new oredict entries. It's likely that your oredict json file does not have the new entries. Please try refreshing the oredict json file.

Ok, let me try.

**Comment by Origins-Eternal** [comment]
It works well, thank you.
