### ISSUE TITLE
Block coordinate NBT data on broken containers

### ISSUE THREAD

**Issue by Primitive-Human** [codetaylor/pyrotech-1.12#405]
#### Issue Description
I've been meaning to ask why some tile entities like the tanks and the barrel store their block coordinates in their NBT data when broken. What purpose does it serve? 

#### What Happens
1. Place a tank (or barrel, or any container that saves coordinate data in NBT).
2. Fill said container with an applicable substance, like a fluid or solid.
3. Break said container. 
4. Inspect the NBT data using a mod that allows its presentation (like JEI Integration). 

#### What You Expect to Happen
I expect the coordinate data to not save to a broken block, as I don't understand what purpose it serves when I intend to move said broken container.

#### Script
- None used. 

#### Crash Log
- No crash or error in the console log. 

#### Affected Versions
* Minecraft: 1.12.2
* Forge: 14.23.5.2860
* CraftTweaker: not applicable
* Dropt: 1.12.2-1.19.3
* Pyrotech: 1.12.2-1.6.5
* Athenaeum: 1.12.2-1.19.5

**Comment by codetaylor** [comment]
It's just some default info serialized by the vanilla TE superclass.
