### ISSUE TITLE
ObsidianAnvil CraftTweaker integration broken

### ISSUE THREAD

**Issue by Gliese-832-c** [codetaylor/pyrotech-1.12#408]
#### Issue Description
When attempting to do import ObsidianAnvil and remove its recipes, it errors saying that there is no such member: ObsidianAnvil

#### What Happens
When attempting to do import ObsidianAnvil and remove its recipes, it gives me the following error:
![image](https://user-images.githubusercontent.com/55159077/204398671-f275619a-90b0-44dc-ae41-58abc33bef1b.png)

#### What You Expect to Happen
It should successfully import ObsidianAnvil.

#### Script
```
import mods.pyrotech.ObsidianAnvil;
ObsidianAnvil.removeAllRecipes();
```

#### Affected Versions
* Minecraft: 1.12.2
* Forge: 14.23.5.2860
* CraftTweaker: 1.12-4.1.20.680
* Dropt: 1.12.2-1.19.3
* Pyrotech: 1.12.2-1.6.5
* Athenaeum: 1.12.2-1.19.5

**Comment by Gliese-832-c** [comment]
Addendum: If you add a recipe to the granite/iron anvil with inheritance set to true, it does *not* get inherited to the obsidian anvil.

**Comment by codetaylor** [comment]
That's a different issue.
