### ISSUE TITLE
Non-Player Harvests of Cobblestone/Stone should have vanilla drops.

### ISSUE THREAD

**Issue by UmbralSurvivor** [codetaylor/pyrotech-1.12#425]
I feel that non-players/fake-players breaking stone, cobblestone, etc should drop their vanilla drops. Pyrotech makes it so Embers (and similar mods) cannot automatically farm Cobblestone with the block breaker.

**Comment by codetaylor** [comment]
You can use Dropt to configure the mod differently if you want.
