### ISSUE TITLE
Refractory oven food recipes take longer than campfire

### ISSUE THREAD

**Issue by SimonMeskens** [codetaylor/pyrotech-1.12#432]
#### Issue Description

The food recipes in the refractory oven are all 2 minutes in JEI. Campfire foods are 1:30 and stone oven foods are 0:30. I assume this is a bug, but I can't seem to track down the relevant code that adds these foods in the source.

#### What Happens

Refractory oven food recipes are 2 minutes in duration

#### What You Expect to Happen

Refractory oven food recipes are equal or lower to the Stone Oven at 30 seconds

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2860
* CraftTweaker: 4.1.20.698
* Dropt: 1.19.3
* Pyrotech: 1.6.11
* Athenaeum: 1.19.6

**Comment by codetaylor** [comment]
By default food recipes in the Stone and Refractory ovens are both 2 minutes. Is it possible that you've tweaked a config setting? Maybe the `COOK_TIME_TICKS` or `INHERITED_STONE_TIER_RECIPE_DURATION_MODIFIER`.

**Comment by SimonMeskens** [comment]
Yup, found the issue, it was somewhere between the computer screen and the back of my head.
