### ISSUE TITLE
Bucket of Ice

### ISSUE THREAD

**Issue by Origins-Eternity** [codetaylor/pyrotech-1.12#442]
#### Issue Description

I will gain bucket of ice(Added by Galaxy Space)  when I right click the ice with wooden, stone, clay and refractory barrel.

#### What Happens

These four types of barrels can be transformed to iron bucket easily.

https://github.com/user-attachments/assets/8a4082dd-444d-48e0-8a53-1bbaf699b1a2

#### What You Expect to Happen

I don't know if it's appropriate to report this issue here, because the bucket of ice is the Galaxy Space's item.  I tried ban these barrels from interacting with ice by Crafttweaker, but it didn't work.

#### Scripts

[Event.zs](https://pastebin.com/D5ugytq6)

#### Affected Versions

* Minecraft:1.12.2
* Forge:14.23.5.2860
* CraftTweaker:4.1.20.700
* Dropt:1.19.4
* Pyrotech:1.6.15
* Athenaeum:1.19.6
* Galaxy Space:2.1.4

**Comment by codetaylor** [comment]
The Galaxy Space mod hooks the `FillBucketEvent` and converts any bucket used on ice into their ice bucket item. Any bucket used on ice will have this problem and there's not much I can do about that. I suggest they check if the bucket is a vanilla bucket before making the conversion.

Here is the code referenced: [GSEventHandler.java](https://github.com/BlesseNtumble/GalaxySpace/blob/dev_1.12.2/src/main/java/galaxyspace/core/events/GSEventHandler.java#L363)

I would report this to the Galaxy Space developers and reference this issue.
