### ISSUE TITLE
Campfire Crafttweaker issue -- setting recipe tick duration does nothing

### ISSUE THREAD

**Issue by Ski-z** [codetaylor/pyrotech-1.12#444]
#### Issue Description

# EDIT: After more testing, it appears that...

```             I:COOK_TIME_TICKS=``` in the .cfg file is ADDED to whatever ticks you include in your script. This isn't in the wiki or in the .cfg, might be nice to include somehwere!

For example:

`Campfire.addRecipe("Charred apple", <minecraft:golden_apple>, <minecraft:apple>, 20);` should make a recipe only require 20 ticks, but it will actually be 20 ticks + whatever default ticks are set in the .cfg

#### Affected Versions

latest PT, version 1.12.2-1.6.16

**Comment by codetaylor** [comment]
Hmm... I don't believe addition is the intended behavior here. I'll take a look.

**Comment by codetaylor** [comment]
The `COOK_TIME_TICKS` is not being added to recipes defined with CraftTweaker. Pyrotech is overwriting custom CT recipes with default recipes using `COOK_TIME_TICKS` when the input has an existing furnace recipe and the input item is a food item. I have changed the behavior to first check for a custom CT recipe before generating a default recipe.

I think the intended use case was to first disallow the campfire from creating a default recipe from the item, then add a custom recipe using CT. In retrospect, that isn't intuitive and it's just extra steps. If a custom recipe is explicitly defined by the user, the system should prioritize the custom recipe.

**Comment by Ski-z** [comment]
Thnk you for the awesome quick fix!
