### ISSUE TITLE
Support for Mystical Mechanics

### ISSUE THREAD

**Issue by SeriousCreeper** [codetaylor/pyrotech-1.12#71]
Would it be possible to get cross-support with Mystical Mechanics (https://minecraft.curseforge.com/projects/mysticalmechanics)? 

Basically being able to power any of the machines that accept gears with the mystical mechanics gearboxes/shafts instead. It also support gears of different quality, maybe that would work with the different gear properties? 

Cheers,
SC

**Comment by Roonas** [comment]
If we're going to go that route, BetterWithMods mechanical power would be neat too. :eyes:

**Comment by Xorbah** [comment]
BIG yes and please to both of these requests. <3

**Comment by codetaylor** [comment]
Pyrotech will not be including any explicit compatibility with third-party mods.
