### ISSUE TITLE
Barrel to catch rain water?

### ISSUE THREAD

**Issue by wizard1399** [codetaylor/pyrotech-1.12#84]
Hello, 
I am working on a pack and found your mod. Seems similar to primal core in theory. One of the things I noticed that was missing is some form of rain collection barrel. It would collect water whenever it rains. You could also have it hold any liquid that is water based. You could also add a feature that would turn blocks under and around the barrel into the mossy version at the cost of a little bit of water lost to the process. Are you actively updating the mod right now?

**Comment by codetaylor** [comment]
I am actively updating the mod right now, but I'm not adding any new content at this time.

A barrel would have to be able to fit into the default progression without diminishing the value of the stone tank and would have to add some kind of stand-alone value to the mod.

Here are the features I'm thinking of:

* made of wood
* holds one bucket of cold fluid
* burns up with hot fluid
* fills up with rain
* leaks / evaporates, ie. slowly loses contents over time
* CrT support for nearby block transforms, ie. cobble to mossy cobble

I am concerned that with this feature set, it doesn't add much value to the mod by itself. Right now it looks like it would just make mossy cobble, which can already be done in the Soaking Pot.

**Comment by wizard1399** [comment]
Imagine you find yourself in a world where there are no natural sources of water. While there is rain, it is not enough to create any bodies of water. All you have are a few survival tools which you can make use of.  
First rule of survival: find a potable water source, food, and shelter.

Since you have thematically laid out your mod as a survival guide, it makes perfect sense to add an early means of collecting water. From a pack makers perspective, the less mods I need to add the better my pack runs. 

Can the stone tank collect water? Assuming there is not a source of water nearby, how does one get water in your survival mod? 

Progression: I see this as happening before the stone tank. In a pack where the natural terrain generation is changed (Skyblock, stone block, wasteland, etc) having an early means of collecting water would be great. Also, the stone tank takes several steps to get: make cobblestone, fire cobblestone to get stone, craft components of recipe, etc.

I would make 1 change to what you stated above: have the barrel hold 2 buckets of water. This would allow the  leaking effect, but would also have a full bucket in the barrel that could be drawn out with a bucket. 

One of the other survival type tasks is preparing leather. You may want to add this to your list of things to add.

**Comment by codetaylor** [comment]
@wizard1399 Thanks for the feedback!

There's some discussion of adding a barrel in with a new forging mechanic in the future, check out #95

**Comment by codetaylor** [comment]
> One of the other survival type tasks is preparing leather.

I may look into leather working features in the future, but that's best left for discussion in a different / new feature thread.

**Comment by codetaylor** [comment]
Barrels are implemented in `1.6.0`
